CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(127) NOT NULL,
  email VARCHAR(127) NOT NULL,
  password VARCHAR(127) NOT NULL,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);
